#!/bin/bash

# Move this to /usr/local/bin/* as it can be very useful when you are testing this in other projects

PACKAGE="$1"
ROOT="/Users/theodor/Projects/bluelibs/packages"

rm -rf node_modules/\@redlibs/$PACKAGE/dist
rm -rf node_modules/\@redlibs/$PACKAGE/src
rm -rf node_modules/\@redlibs/$PACKAGE/package.json

cp -r $ROOT/$PACKAGE/dist "./node_modules/@redlibs/$PACKAGE/dist"
cp -r $ROOT/$PACKAGE/src "./node_modules/@redlibs/$PACKAGE/src"
cp -r $ROOT/$PACKAGE/package.json "./node_modules/@redlibs/$PACKAGE/package.json"
